use database RAW;
use schema ALCHEMER;
select get_ddl('table','SURVEY_DATA_SUB_QUESTION');


create or replace TABLE SURVEY_REPORT (
	_FIVETRAN_ID VARCHAR(256) NOT NULL,
	_FIVETRAN_DELETED BOOLEAN,
	SURVEY_ID NUMBER(38,0),
	NAME VARCHAR(256),
	RESPONSES NUMBER(38,0),
	LAST_RUN VARCHAR(256),
	ID VARCHAR(256),
	TYPE VARCHAR(256),
	PUBLISH_LINK VARCHAR(256),
	VERSION NUMBER(38,0),
	STATUS VARCHAR(256),
	_FIVETRAN_SYNCED TIMESTAMP_TZ(9),
	primary key (_FIVETRAN_ID),
	foreign key (SURVEY_ID) references RAW.ALCHEMER.SURVEY(ID)
);
select * from RAW.INFORMATION_SCHEMA.COLUMNS where TABLE_CATALOG = 'RAW' and TABLE_SCHEMA = 'ALCHEMER' and TABLE_NAME = 'SURVEY_DATA';


SELECT *,TO_NUMERIC(CONCAT(TO_VARCHAR(SURVEY_ID),TO_VARCHAR(SURVEY_RESPONSE_ID),TO_VARCHAR(ID))) as _surrogate_key FROM RAW.ALCHEMER.SURVEY_DATA;

SECTION_ID,ANSWER_ID,ANSWER,ORIGINAL_ANSWER,QUESTION,SURVEY_RESPONSE_ID,TYPE,_FIVETRAN_SYNCED,_FIVETRAN_DELETED,SHOWN,
ID,SURVEY_ID;


--TO_NUMERIC(CONCAT(TO_VARCHAR(SURVEY_ID),TO_VARCHAR(ID))) as _surrogate_key
--TO_NUMERIC(CONCAT(TO_VARCHAR(SURVEY_ID),TO_VARCHAR(SURVEY_RESPONSE_ID),TO_VARCHAR(ID))) as _surrogate_key;


SELECT ID,SURVEY_ID,SURVEY_RESPONSE_ID,SECTION_ID,ANSWER_ID,ANSWER,ORIGINAL_ANSWER,QUESTION,TYPE,_FIVETRAN_SYNCED,_FIVETRAN_DELETED,SHOWN, TO_NUMERIC(CONCAT(TO_VARCHAR(ID),TO_VARCHAR(SURVEY_ID),TO_VARCHAR(SURVEY_RESPONSE_ID))) as _surrogate_key FROM RAW.ALCHEMER.SURVEY_DATA WHERE TO_NUMERIC(CONCAT(TO_VARCHAR(ID),TO_VARCHAR(SURVEY_ID),TO_VARCHAR(SURVEY_RESPONSE_ID))) NOT IN (SELECT _surrogate_key FROM STAGING.ALCHEMER.SURVEY_DATA);




select ID,count(*) FROM RAW.ALCHEMER.OPTION group by 1 order by 2;

select question_id,count(*) FROM RAW.ALCHEMER.OPTION group by 1 order by 2;

select id,count(*) FROM RAW.ALCHEMER.QUESTION group by 1 order by 2;


select id,count(*) FROM RAW.ALCHEMER.SURVEY_STATISTIC group by 1 order by 2;

select id,count(*) FROM RAW.ALCHEMER.SURVEY_RESPONSE group by 1 order by 2 desc;

select * from RAW.ALCHEMER.SURVEY_PAGE limit 30;
select count(*) from raw.alchemer.survey_theme;


select  ID,SURVEY_ID,SURVEY_RESPONSE_ID from RAW.ALCHEMER.SURVEY_DATA  where ID = 731;

select user_id,count(*) FROM RAW.KUSTOMER.USER_ROLE group by 1 order by 2 desc;

select * from raw.kustomer.user_role;


-- Payments (fundrasing page -> event -> id) = Pages Event ID
-- Donations (FundraisingPageId) =  Pages (ID)
-- Payments (PaymentRef) = Donations (DonationPaymentReference)